### ISSUE TITLE
安装pylibpcap-0.6.4 出错

### ISSUE THREAD

**Issue by XEYES** [ysrc/GourdScanV2#12]
$python setup.py install
running install
running build
running build_ext
building '_pcapmodule' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DSWIG_COBJECT_TYPES -I/usr/include/python2.7 -c pcap.c -o build/temp.linux-x86_64-2.7/pcap.o
pcap.c: In function ‘SWIG_Python_AddErrorMsg’:
pcap.c:853:5: error: format not a string literal and no format arguments [-Werror=format-security]
     PyErr_Format(PyExc_RuntimeError, mesg);
     ^~~~~~~~~~~~
cc1: some warnings being treated as errors
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

已安装libpcap，debain 跟ubuntu 16均出现这个问题，请问如何解决。

**Comment by ghost** [comment]
apt-get install libpcap-dev
apt-get install python-libpcap

**Comment by XEYES** [comment]
谢谢回复。

已安装 libpcap-dev
安装 apt-get install python-libpcap 后问题如故，求解。

**Comment by ghost** [comment]
试试 apt-get install python-dev

**Comment by XEYES** [comment]
谢谢，已经安装成功。 不过出现新的问题gourdscan/conf/conf.json文件无法找到，能否贴一下你的conf.json内容。


└──╼ $gourdscan
Traceback (most recent call last):
  File "/usr/local/bin/gourdscan", line 11, in <module>
    load_entry_point('gourdscan==2.1', 'console_scripts', 'gourdscan')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/cli.py", line 5, in <module>
    from gourdscan.web.app import main
  File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/web/app.py", line 14, in <module>
    from gourdscan.web.urls import url_patterns
  File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/web/urls.py", line 3, in <module>
    import handlers.main
  File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/web/handlers/main.py", line 11, in <module>
    from gourdscan.lib.redisopt import conn
  File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/lib/redisopt.py", line 19, in <module>
    with open(CHECK_CONF_FILE) as conf:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/conf/conf.json'

**Comment by ghost** [comment]
- 试了下 `python setup.py install` 导致的结果有些错误
- 你可以试试 `cp -r /你git clone的地址/GourdScanV2/gourdscan/conf  /usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/` 手动把 conf 目录复制过去
- 如果不能解决就不要用 `python setup.py install` 安装的方式运行了，直接运行吧

**Comment by XEYES** [comment]
按楼上兄台的方法已经成功运行gourdscan-2.1，但是在登录后出现了错误。

[E 170301 15:23:56 web:1548] Uncaught exception POST /login (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/login', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://localhost:8000', 'Content-Length': '33', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Host': 'localhost:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8000/login', 'Cache-Control': 'max-age=0', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'})
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/web/handlers/main.py", line 46, in post
        cookie = session.new("self.request.remote_ip")
      File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/lib/session.py", line 19, in new
        return md5.new(config.load()["cookie_secret"] + str(time.time()) + ip).hexdigest()
    AttributeError: 'builtin_function_or_method' object has no attribute 'new'

**Comment by ghost** [comment]
试试直接在项目目录下运行，如
`python GourdScanV2/gourdscan/web/app.py`

**Comment by XEYES** [comment]
python GourdScanV2/gourdscan/web/app.py
问题如故。


 AttributeError: 'builtin_function_or_method' object has no attribute 'new'

**Comment by Ge0metryAI** [comment]
![qq 20170301154341](https://cloud.githubusercontent.com/assets/15847202/23450385/dcc00216-fe95-11e6-8ba1-a28ad0c712d6.png)

**Comment by ghost** [comment]
- 忽然觉得，出了这些问题，凸显了 docker 的重要性

**Comment by imfht** [comment]
@donghouhe docker也报错...

**Comment by rangeme** [comment]
@jhhd88 @XEYES @fiht 马上会更改目录结构，重新升级一下。
另外，这个错误我这里没出现，尝试一下运行cli.py，看看你conf.json有没有问题
