### ISSUE TITLE
读取不到rules

### ISSUE THREAD

**Issue by Ge0metryAI** [ysrc/GourdScanV2#19]
`    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/web/handlers/base.py", line 14, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/web/handlers/main.py", line 102, in get
        rules[i] = config.rule_read(i)
      File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/lib/config.py", line 49, in rule_read
        with open(os.path.join(RULES_PATH, name, '.rule')) as con:
    IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/conf/rules/sqlitime/.rule'
`

**Comment by linxi0428** [comment]
这个是代码上有些问题，我已经提交pull了，作者也接受了，你重新下载代码试试
