### ISSUE TITLE
删除waiting时500

### ISSUE THREAD

**Issue by Ge0metryAI** [ysrc/GourdScanV2#22]
Uncaught exception GET /del?type=waiting (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/del?type=waiting', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0', 'Connection': 'keep-alive', 'Referer': 'http://127.0.0.1:8000/list?type=waiting', 'Cookie': 'ysrc_token=22f8da9b10a311c70ab8aae5cce002e3', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/web/handlers/base.py", line 14, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/gourdscan/web/handlers/main.py", line 292, in get
        conn.delete(del_type)
      File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 841, in delete
        return self.execute_command('DEL', *names)
      File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 573, in execute_command
        return self.parse_response(connection, command_name, **options)
      File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 585, in parse_response
        response = connection.read_response()
      File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 582, in read_response
        raise response
    ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

**Comment by guixiaomin** [comment]
哥们这么晚还在卖力的研究。。。

**Comment by rangeme** [comment]
@jhhd88 大兄弟，这个应该是redis的问题，你换个redis试试
