### ISSUE TITLE
今天运行突然报错这个，

### ISSUE THREAD

**Issue by bubaidongfang** [ysrc/GourdScanV2#30]
D:\Python27\GourdScanV2>python gourdscan.py
Traceback (most recent call last):
  File "gourdscan.py", line 25, in <module>
    from web.urls import url_patterns
  File "D:\Python27\GourdScanV2\web\urls.py", line 3, in <module>
    import handlers.main
  File "D:\Python27\GourdScanV2\web\handlers\main.py", line 17, in <module>
    from proxy import pyscapy, mix_proxy, proxy_io
  File "D:\Python27\GourdScanV2\proxy\pyscapy.py", line 11, in <module>
    from scapy.all import *
  File "D:\Python27\lib\site-packages\scapy\all.py", line 16, in <module>
    from scapy.arch import *
  File "D:\Python27\lib\site-packages\scapy\arch\__init__.py", line 83, in <modu
le>
    from scapy.arch.windows import *
  File "D:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 318,
 in <module>
    IFACES.load_from_powershell()
  File "D:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 270,
 in load_from_powershell
    for i in get_windows_if_list():
  File "D:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 206,
 in get_windows_if_list
    for line in query)
  File "D:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 205,
 in <genexpr>
    (dict(zip(['name', 'win_index', 'description', 'guid', 'mac'], line))
  File "D:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 53,
in _exec_query_ps
    l.append(line.split(':', 1)[1].strip())
IndexError: list index out of range

**Comment by rangeme** [comment]
这个明显是scapy报错，你重装这个模块试试
